# Generated by Django 5.1.1 on 2024-12-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
